<?php

namespace restapi;

class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init();
    }

    public function runAction($route, $params = [])
    {
        die($route);
        return parent::runAction($route, $params); // TODO: Change the autogenerated stub
    }
}
