#!/usr/bin/env php
<?php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
exit((new yii\console\Application(require(__DIR__ . '/modules/console/configs/config.php')))->run());

# yiic command -e DEV -d 
# yiic command --env=dev --debug